### ISSUE TITLE
disable dependabot?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/example-notebooks#54]
We have requirements.txt for various notebooks.
- dependabot sends multitude PRs: https://github.com/dandi/example-notebooks/pulls?q=is%3Apr+dependabot+
- @bendichter merged some, some remain open
- there is no guarantee that notebooks would work with more recent versions of dependencies
- there is no guarantee that results would be reproducible with newer versions
- there is no guarantee that new upgraded versions would be coinstallable and compatible with older versions of the others

with that in mind, I think we should just disable dependabot for this repo and close all those PRs unmerged

If there is no feedback/counter arguments, I will do that in a week

**Comment by bendichter** [comment]
Yes, I think that's fine. I thought it would be a quick thing but the PRs keep on coming
